# Chapter 1 实践基础

## 1.1 导入 package

In [30]:
import torch
import numpy as np

## 1.2 张量

In [31]:
array = [2.0, 3.0, 4.0]
array2torch = torch.tensor(array)
array2torch

tensor([2., 3., 4.])

In [32]:
matrix = [[2.0, 3.0, 4.0], [5.0, 6.0, 7.0]]
matrix2torch = torch.tensor(matrix)
matrix2torch

tensor([[2., 3., 4.],
        [5., 6., 7.]])

In [33]:
array2torch.shape, matrix2torch.shape, array2torch.ndim, matrix2torch.ndim

(torch.Size([3]), torch.Size([2, 3]), 1, 2)

In [34]:
array2torch.size()

torch.Size([3])

In [35]:
zero_torch = torch.zeros([4, 3])
zerolike_torch = torch.zeros_like(matrix2torch)
one_torch = torch.ones([4, 3])
full_torch = torch.full([4, 3], 10.)
zero_torch, zerolike_torch, one_torch, full_torch

(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[10., 10., 10.],
         [10., 10., 10.],
         [10., 10., 10.],
         [10., 10., 10.]]))

In [36]:
arrange_torch = torch.arange(start=1, end=6, step=2)
linspace_torch = torch.linspace(start=0, end=10, steps=5)
arrange_torch, linspace_torch

(tensor([1, 3, 5]), tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000]))

In [37]:
ndim_3_torch = torch.tensor([[[1, 2, 3, 4, 5],
                               [6, 7, 8, 9, 10]],
                               [[11, 12, 13, 14, 15],
                               [16, 17, 18, 19, 20]],
                               [[21, 22, 23, 24, 25],
                               [26, 27, 28, 29, 30]]])
ndim_3_torch.shape

torch.Size([3, 2, 5])

In [38]:
reshape_torch = ndim_3_torch.reshape([2, 3, 5])
reshape_torch, reshape_torch.shape

(tensor([[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10],
          [11, 12, 13, 14, 15]],
 
         [[16, 17, 18, 19, 20],
          [21, 22, 23, 24, 25],
          [26, 27, 28, 29, 30]]]),
 torch.Size([2, 3, 5]))

In [39]:
reshape_torch = ndim_3_torch.reshape([-1, 2])
reshape_torch, reshape_torch.shape

(tensor([[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10],
         [11, 12],
         [13, 14],
         [15, 16],
         [17, 18],
         [19, 20],
         [21, 22],
         [23, 24],
         [25, 26],
         [27, 28],
         [29, 30]]),
 torch.Size([15, 2]))

In [40]:
reshape_torch = ndim_3_torch.reshape([-1, 5, 2])
reshape_torch, reshape_torch.shape

(tensor([[[ 1,  2],
          [ 3,  4],
          [ 5,  6],
          [ 7,  8],
          [ 9, 10]],
 
         [[11, 12],
          [13, 14],
          [15, 16],
          [17, 18],
          [19, 20]],
 
         [[21, 22],
          [23, 24],
          [25, 26],
          [27, 28],
          [29, 30]]]),
 torch.Size([3, 5, 2]))

In [41]:
unsqueeze_torch = torch.unsqueeze(ndim_3_torch, axis=0)
unsqueeze_torch, unsqueeze_torch.shape

(tensor([[[[ 1,  2,  3,  4,  5],
           [ 6,  7,  8,  9, 10]],
 
          [[11, 12, 13, 14, 15],
           [16, 17, 18, 19, 20]],
 
          [[21, 22, 23, 24, 25],
           [26, 27, 28, 29, 30]]]]),
 torch.Size([1, 3, 2, 5]))

In [42]:
torch.tensor(1).dtype, torch.tensor(1.).dtype

(torch.int64, torch.float32)

In [43]:
float32_torch = torch.tensor(1.)
int64_torch = torch._cast_Long(float32_torch)
float32_torch.dtype, int64_torch.dtype

(torch.float32, torch.int64)

In [44]:
cpu_tensor = torch.tensor(1., device='cpu')
gpu_tensor = torch.tensor(1., device='cuda:0')
cpu_tensor, gpu_tensor

(tensor(1.), tensor(1., device='cuda:0'))

In [45]:
cpu_tensor = cpu_tensor.to('cuda:0')
cpu_tensor

tensor(1., device='cuda:0')

In [46]:
np_torch = torch.tensor([1.0, 2.0])
np_torch.numpy()

array([1., 2.], dtype=float32)

In [47]:
split_torch = torch.tensor([1., 2., 3., 4., 5., 6., 7., 8.])
split_torch[0], split_torch[-1], split_torch[::2], split_torch[:-1], split_torch.__reversed__()

(tensor(1.),
 tensor(8.),
 tensor([1., 3., 5., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 tensor([8., 7., 6., 5., 4., 3., 2., 1.]))

In [48]:
split_torch = torch.tensor([[[1., 2., 3., 4., 5., 6., 7., 8.], [1., 2., 3., 4., 5., 6., 7., 8.]], [[1., 2., 3., 4., 5., 6., 7., 8.], [1., 2., 3., 4., 5., 6., 7., 8.]]])
split_torch.shape, split_torch[1, :]

(torch.Size([2, 2, 8]),
 tensor([[1., 2., 3., 4., 5., 6., 7., 8.],
         [1., 2., 3., 4., 5., 6., 7., 8.]]))

In [49]:
x = torch.tensor([[-1.1, 2.2], [3.3, 4.4]])
y = torch.tensor([[5.5, 6.6], [7.7, 8.8]])
torch.add(x, y), x.add(y), x + y

(tensor([[ 4.4000,  8.8000],
         [11.0000, 13.2000]]),
 tensor([[ 4.4000,  8.8000],
         [11.0000, 13.2000]]),
 tensor([[ 4.4000,  8.8000],
         [11.0000, 13.2000]]))

In [50]:
x.abs(), x.ceil(), x.floor(), x.round(), x.exp(), x.log(), x.reciprocal(), x.square(), x.sqrt()


(tensor([[1.1000, 2.2000],
         [3.3000, 4.4000]]),
 tensor([[-1.,  3.],
         [ 4.,  5.]]),
 tensor([[-2.,  2.],
         [ 3.,  4.]]),
 tensor([[-1.,  2.],
         [ 3.,  4.]]),
 tensor([[ 0.3329,  9.0250],
         [27.1126, 81.4509]]),
 tensor([[   nan, 0.7885],
         [1.1939, 1.4816]]),
 tensor([[-0.9091,  0.4545],
         [ 0.3030,  0.2273]]),
 tensor([[ 1.2100,  4.8400],
         [10.8900, 19.3600]]),
 tensor([[   nan, 1.4832],
         [1.8166, 2.0976]]))

In [51]:
y, x, x % y

(tensor([[5.5000, 6.6000],
         [7.7000, 8.8000]]),
 tensor([[-1.1000,  2.2000],
         [ 3.3000,  4.4000]]),
 tensor([[4.4000, 2.2000],
         [3.3000, 4.4000]]))

In [52]:
x.sin(), x.cos(), x * y, y % x, x.max(), x.min(), x.prod(), x.sum()

(tensor([[-0.8912,  0.8085],
         [-0.1577, -0.9516]]),
 tensor([[ 0.4536, -0.5885],
         [-0.9875, -0.3073]]),
 tensor([[-6.0500, 14.5200],
         [25.4100, 38.7200]]),
 tensor([[-1.1921e-07,  2.2000e+00],
         [ 1.1000e+00,  0.0000e+00]]),
 tensor(4.4000),
 tensor(-1.1000),
 tensor(-35.1384),
 tensor(8.8000))

In [53]:
(1/torch.zeros([0, 0, 0])).isfinite(), x.allclose(y)

(tensor([], size=(0, 0, 0), dtype=torch.bool), False)

In [54]:
x = torch.ones([2, 3, 1, 5])
y = torch.ones([3, 4, 1])
z = x + y
z # broadcast

tensor([[[[2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.]],

         [[2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.]],

         [[2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.]]],


        [[[2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.]],

         [[2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.]],

         [[2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.]]]])

In [55]:
x = torch.randn([2, 3])
y = torch.randn([3, 2])
x, y, x.t(), x.transpose(1, 0), x.norm(), x.matmul(y)

(tensor([[0.2629, 1.5925, 0.1899],
         [0.8201, 2.1017, 2.5966]]),
 tensor([[ 0.2285, -0.6448],
         [ 0.2653, -0.6893],
         [-1.0389, -0.4237]]),
 tensor([[0.2629, 0.8201],
         [1.5925, 2.1017],
         [0.1899, 2.5966]]),
 tensor([[0.2629, 0.8201],
         [1.5925, 2.1017],
         [0.1899, 2.5966]]),
 tensor(3.8043),
 tensor([[ 0.2854, -1.3477],
         [-1.9524, -3.0776]]))

## 1.3 算子

In [56]:
import math

class Op(object):
    def __init__(self):
        pass

    def __call__(self, inputs):
        return self.forward(inputs)
    
    def forward(self, inputs):
        raise NotImplementedError
    
    def backward(self, outputs_grads):
        raise NotImplementedError

class add(Op):
    def __init__(self):
        super(add, self).__init__()
    
    def __call__(self, x, y):
        return self.forward(x, y)
    
    def forward(self, x, y):
        self.x = x
        self.y = y
        outputs = x + y
        return outputs
    
    def backward(self, grads):
        grads_x = grads * 1
        grads_y = grads * 1
        return grads_x, grads_y

class multiply(Op):
    def __init__(self):
        super(multiply, self).__init__()

    def __call__(self, x, y):
        return self.forward(x, y)
    
    def forward(self, x, y):
        self.x = x
        self.y = y
        return x * y
    
    def backward(self, grads):
        grads_x = grads * self.y
        grads_y = grads * self.x
        return grads_x, grads_y
    
class exp(Op):
    def __init__(self):
        super(exp, self).__init__()

    def __call__(self, x):
        return self.forward(x)
    
    def forward(self, x):
        self.x = x
        return math.exp(x)
    
    def backward(self, grads):
        grads_x = grads * math.exp(self.x)
        return grads_x

In [57]:
a, b, c, d = 2, 3, 2, 2
multiply_op = multiply()
add_op = add()
exp_op = exp()

g = exp_op(add_op(multiply_op(a, b), multiply_op(c, d)))
g

22026.465794806718

In [58]:
a = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(3.0, requires_grad=True)
c = a * b
c.backward()
a.grad, b.grad, c.grad

C:\Users\huang\AppData\Local\Temp\ipykernel_19208\3477281545.py:5: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\build\aten\src\ATen/core/TensorBody.h:494.)
  a.grad, b.grad, c.grad


(tensor(3.), tensor(2.), None)